### ISSUE TITLE
功能分配

### ISSUE THREAD

**Issue by grassking100** [grassking100/Canvas#2]
目前有兩個地方GUI和Canvas有衝突到
    (1)Player, City之間的互動是由誰控制
    (2)Canvas的初始化動作該分配多少給GUI
關於問題一:
    Canvas該不該判斷Player和Player之間, 還有Player和City之間的接觸,接觸後的動作執行,狀態改變由誰負責控制

關於問題二:
    GUI該不該負責圖片路徑判斷,還有 Player, City圖片初始化的功能

**Comment by dollychu** [comment]
(1) 互動不是伺服器來做的事嗎
接觸應該涵蓋在collision()的判斷 不過要先問做伺服器的有沒有考慮到這個問題 如果我們只負責顯示接收到的x,y座標的話
(2) 初始化應該在cavas裡面沒錯 GUI只負責介面
圖片路徑判斷是什麼意思呢

**Comment by grassking100** [comment]
關於問題一:
    a.server只負責client端之間訊息的傳送,還有global事件(各城市的選票,突發事件)的產生
    b.問題一所述皆是由client端執行,並將執行的結果通知其他client和server
    c.canvas目前是可以接收UI的訊號(w,a,s,d,其他玩家的位置)並顯示圖片即可,但是玩家之間是否有接
       觸,接觸後的玩家狀態(諸如金錢的增加)是該由UI處理還是canvas處理?
關於問題二:
    如果是這樣我就限制UI控制圖片來源的功能,並由canvas內部負責處理

**Comment by dollychu** [comment]
原本玩家狀態是由ＵＩ顯示的，考慮到訊息最後要經過ＵＩ傳回server，似乎由ＵＩ來處理比較合理。
所以是否接觸由canvas判斷，再把訊息傳給ＵＩ，由ＵＩ執行事件。

**Comment by grassking100** [comment]
你說的有道理,那問題就解決了
